name: Final project validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-project
  cancel-in-progress: true

env:
  REPOSITORY_TYPE: public
  FINAL_PROJECT_TAG: "[PROJECT]"
  MODEL_URL: "https://github.com/fipl-hse/2024-2-level-ctlr/releases/download/v1.0.0/russian-syntagrus-ud-2.0-170801.udpipe"
  MODEL_PATH: "lab_6_pipeline/assets/model"

jobs:
  check-conditions:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}

    steps:
      - name: Check if workflow should run
        id: check
        run: |
          if [[ "$REPOSITORY_TYPE" == "admin" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          elif [[ -n "${{ github.event.pull_request.title }}" ]] && \
               [[ "${{ github.event.pull_request.title }}" == *"$FINAL_PROJECT_TAG"* ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  validate-student-data:
    runs-on: ubuntu-latest
    needs: check-conditions
    if: needs.check-conditions.outputs.should_run == 'true'

    steps:
      - uses: actions/checkout@v4
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.11
      - name: Download UDPipe model
        run: |
          mkdir -p "$MODEL_PATH" 
          wget -O $MODEL_PATH/russian-syntagrus-ud-2.0-170801.udpipe $MODEL_URL
      - name: Student data processing
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          
          if [[ $(python admin_utils/skip_stage.py --lab-path final_project) ]]; then
            exit 0
          fi

          python final_project/main.py
          python admin_utils/final_project/checker.py final_project/dist/auto_annotated.conllu
      - name: Archive annotated data
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: auto-annotated-dataset
          path: |
            final_project/dist
          retention-days: 5
